---
- name: Install Zabbix Server
  hosts: ZabbixVM
  become: true  # Run tasks as a superuser (sudo)

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest

    - name: Install required packages
      yum:
        name:
          - httpd
          - mariadb-server
          - mariadb
          - mariadb-server
          - php
          - php-mysql
          - php-bcmath
          - php-mbstring
          - php-gd
          - php-xml
          - php-ldap
          - php-json
          - net-snmp
          - net-snmp-utils
          - wget
          - unzip
        state: present

    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - mariadb

    - name: Download and install Zabbix repository
      get_url:
        url: https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm
        dest: /tmp/zabbix-release.rpm

    - name: Install Zabbix repository
      yum:
        name: /tmp/zabbix-release.rpm
        state: present

    - name: Install Zabbix Server, Frontend, and Agent
      yum:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-agent
        state: present

    - name: Configure MariaDB for Zabbix
      mysql_db:
        name: zabbix
        state: present
      become_user: root
      become_method: sudo

    - name: Import Zabbix database schema
      mysql_db:
        name: zabbix
        state: import
        target: /usr/share/doc/zabbix-server-mysql-5.4.0/create.sql.gz
      become_user: root
      become_method: sudo

    - name: Configure Zabbix Server
      template:
        src: zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
      notify:
        - restart zabbix-server

    - name: Configure Zabbix PHP settings
      template:
        src: zabbix.conf.php.j2
        dest: /etc/zabbix/web/zabbix.conf.php
    
    - name: Remove zabbix config file
      become: yes
      file:
          path: /etc/zabbix/zabbix_agentd.conf
          state: absent

      
    - name: Create new zabbix config file from template
      become: yes
      template:
          src: "/home/opc/zabbix_agentd.conf.j2"
          dest: "/etc/zabbix/zabbix_agentd.conf"


    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted

  handlers:
    - name: restart zabbix-server
      systemd:
        name: zabbix-server
        state: restarted
